repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-merge-conflict
  - id: check-added-large-files
    exclude: uv.lock
  - id: check-yaml
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
    exclude: &exclude_pre_commit_hooks >
      (?x)^(
        tests/.*(?<!\.py)$|
        docs/source/.+\.aiida/repo/.+|
        CHANGELOG.md|
      )$
  - id: fix-encoding-pragma
    args: [--remove]
  - id: mixed-line-ending
    args: [--fix=lf]
  - id: trailing-whitespace
    exclude: *exclude_pre_commit_hooks

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.37.0
  hooks:
  - id: check-github-workflows

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.4
  hooks:
  - id: ruff-format
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix, --show-fixes]

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.16.0
  hooks:
  - id: pretty-format-toml
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix]
    exclude: >-
      (?x)^(
        tests/.*|
        environment.yml|
      )$
